belajar_dbt:
  outputs:
    dev:
      dbname: Selling
      host: localhost
      pass: "1234"
      port: 5433
      schema: global
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: Selling
      host: localhost
      pass: "1234"
      port: 5433
      schema: global
      threads: 1
      type: postgres
      user: postgres
  target: dev